### ISSUE TITLE
Error for CURL calling freme-ner

### ISSUE THREAD

**Issue by katia-vistatec** [freme-project/freme-docker#40] opened 2016-11-30 16:47 UTC
After Docker installation:

When calling curl -X POST --header "Content-Type: text/html" --header "Accept: text/html" --data "@input.txt" "http://localhost:4000/e-entity/freme-ner/documents?language=en&dataset=dbpedia&mode=spot%2Clink"

I get an error:

{
  "exception": "eu.freme.common.exception.UnsupportedRDFSerializationException",
  "path": "/e-entity/freme-ner/documents",
  "message": "Parameter informat has invalid value \"text/html\". Please use one of: json-ld, application/rdf+xml, turtle, text/n3, n-triples or text/plain",
  "error": "Bad Request",
  "status": 400,
  "timestamp": 1480523875305
}

Is there something wrong with this call?
Can someone in case try to reproduce the issue in their Docker installation?

The original call on freme-dev:

curl -X POST --header "Content-Type: text/html" --header "Accept: text/html" --data "@input.txt" "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&mode=spot%2Clink"

works.

**Comment by jnehring** [comment] 2016-12-01 12:25
Your curl was correct. I could reproduce the error. There was a configuration issue that I have fixed. Now the error is fixed on our docker installation. I have already pushed a new docker image for the broker.

Can you update the broker and check if this solves your problem?

**Comment by katia-vistatec** [comment] 2016-12-01 14:36
For now It gives me an error.
[Error.txt](https://github.com/freme-project/freme-docker/files/624856/Error.txt)

**Comment by jnehring** [comment] 2016-12-01 14:53
I will take a look at the problem.

**Comment by jnehring** [comment] 2016-12-05 09:05
I logged in to the server

1) I exported the environement variable again (export FREME_DISTRIBUTION=standard). It was not set and docker complained.
2) Then I checked config.env file. The first line should be a comment so I added `#` to the first line. But I am not sure if I accidently removed the comment myself before adding it again.
3) The Solr server could not start properly which I could see in the logs ([docker logs command](https://docs.docker.com/engine/reference/commandline/logs/)). Therefore I updated the access rights	using `sudo chmod o+rw -R /opt/freme-data/*`
4) I stopped the whole installation using `docker stop`. Then I did `docker-compose up -d --no-deps` and it re-created three containers.

Then I ran the CURL request 

```
curl -X POST --header "Content-Type: text/html" --header "Accept: text/html" --data "<p>Welcome to Dublin.</p>" "http://localhost:4000/e-entity/freme-ner/documents?language=en&dataset=dbpedia&mode=spot%2Clink"
```

and it worked.

@katia-vistatec please check if the issue is solved for you.

I added the docker logs command to our [docker documentation](https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/use-freme-docker.html) because I think that this might have helped to discover the problem with Solr.

**Comment by katia-vistatec** [comment] 2016-12-05 09:27
Yes it works, thanks!

**Comment by jnehring** [comment] 2016-12-05 09:33
Ok. So as far as I know the VTEC docker installation works now?

You can try the [freme test suite](https://github.com/freme-project/freme-docker/issues/39) for a quick check on multiple freme services.

**Comment by jnehring** [comment] 2016-12-15 10:13
We can close this issue. This refers to the docker installation and it was fixed there. The issue is no longer valid.

**Closed as completed by jnehring** 2016-12-15 10:13 UTC
